version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "Android/EasyBudget/build.gradle" }}-{{ checksum  "Android/EasyBudget/app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: Android/EasyBudget/gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "Android/EasyBudget/build.gradle" }}-{{ checksum  "Android/EasyBudget/app/build.gradle" }}
      - run:
          name: Run Tests
          command: Android/EasyBudget/gradlew lint test
      - store_artifacts:
          path: Android/EasyBudget/app/build/reports
          destination: reports
      - store_test_results:
          path: Android/EasyBudget/app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples